name: "End-to-End Tests"

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run e2e tests
        run: npm run test:e2e
