name: "Release"

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:coverage
      
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
      
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: ./node_modules/.bin/semantic-release