name: "Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: npm install
        run: npm ci

      - name: build package
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.4