name: "Tests"

on: ["pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Jest coverage report
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npx jest --config=jest.json --testLocationInResults --colors --silent --ci --coverage --coverageReporters='text' --coverageReporters='text-summary' --json --outputFile=report.json
